apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  # deployment labels
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      tier: database
  # This is pod definition
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
        tier: database
    spec:
      serviceAccount: roboshop-mysql-secret-reader
      volumes:
      - name: mysql-secret
        emptyDir: {}
      containers:
      - name: mysql
        image: joindevops/mysql:v2
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmp
          name: mysql-secret
      initContainers:
      - name: fetch-secret
        image: amazon/aws-cli
        command:
        - sh
        - -c
        - |
           aws secretsmanager get-secret-value \
          --secret-id roboshop/mysql/password \
          --region us-east-1 \
          --query SecretString --output text > /tmp/secret.json
        # extract MYSQL_ROOT_PASSWORD without jq
        MYSQL_PASS=$(cat /tmp/secret.json | sed -e 's/.*"MYSQL_ROOT_PASSWORD":"\([^"]*\)".*/\1/')
        echo $MYSQL_PASS > /tmp/mysql-root-password
        echo "Secret written to /tmp/mysql-root-password"
  volumeMounts:
    - mountPath: /tmp
      name: mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container port